# Build script for Evothings Eddystone plugin JavaScript files.

require "fileutils"

include FileUtils::Verbose

### File helpers

def fileRead(filePath)
	File.open(filePath, "r") { |f|
		s = f.read
		if(RUBY_VERSION >= "1.9")
			return s.force_encoding("UTF-8")
		else
			return s
		end
	}
end

def fileWrite(destFile, content)
	File.open(destFile, "w") { |f| f.write(content) }
end

### Merge library files

def mergeFiles
	libsPath = "../evothings-examples/resources/libs/evothings/"
	utiljs = fileRead(libsPath + "util/util.js")
	easyblejs = fileRead(libsPath + "easyble/easyble.js")
	eddystonejs = fileRead(libsPath + "eddystone/eddystone.js")
	evothingsbasejs = fileRead("js/evothings-base.js")
	eddystoneexportsjs = fileRead("js/eddystone-exports.js")
	fileSep = "\n\n"
	eddystonepluginjs =
		"// This file was generated by buildEddystonePluginJS.rb" + fileSep +
		evothingsbasejs + fileSep +
		utiljs  + fileSep +
		easyblejs + fileSep +
		eddystonejs + fileSep +
		eddystoneexportsjs
	fileWrite("js/eddystone-plugin.js", eddystonepluginjs)
end

mergeFiles
